package api

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"

	"github.com/google/uuid"
	"github.com/martyushova/posts/internal/model"
	gql "github.com/martyushova/posts/internal/model/graphql"
)

// CreatePost создает новый пост
func (r *mutationResolver) CreatePost(ctx context.Context, input gql.PostInput) (*model.Post, error) {
	// В реальной системе мы бы получали id пользователя через токен, который он передает
	userID := uuid.NewString()
	post, err := r.postService.CreatePost(ctx, userID, &model.Post{
		Text:            input.Text,
		CommentsAllowed: input.CommentsAllowed,
	})
	if err != nil {
		return nil, handleError(err)
	}

	return post, nil
}

// CreateComment is the resolver for the createComment field.
func (r *mutationResolver) CreateComment(ctx context.Context, input gql.CommentInput) (*model.Comment, error) {
	// В реальной системе мы бы получали id пользователя через токен, который он передает
	userID := uuid.NewString()
	post, err := r.commentService.CreateComment(ctx, userID, &model.Comment{
		Text:            input.Text,
		PostID:          input.PostID,
		ParentCommentID: input.ParentCommentID,
	})
	if err != nil {
		return nil, handleError(err)
	}

	return post, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
