package api

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"

	"github.com/martyushova/posts/internal/model"
)

// Comments получение списка комментариев
func (r *postResolver) Comments(ctx context.Context, obj *model.Post, limit int32, offset int32) ([]*model.Comment, error) {
	comments, err := r.commentService.ListComments(ctx, obj.ID, limit, offset)
	if err != nil {
		return nil, handleError(err)
	}

	return comments, nil
}

// Post returns PostResolver implementation.
func (r *Resolver) Post() PostResolver { return &postResolver{r} }

type postResolver struct{ *Resolver }
