package api

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"fmt"

	"github.com/google/uuid"
	"github.com/martyushova/posts/internal/model"
)

// Posts is the resolver for the posts field.
func (r *queryResolver) Posts(ctx context.Context) ([]*model.Post, error) {
	posts, err := r.postService.ListPosts(ctx)
	if err != nil {
		return nil, handleError(err)
	}
	return posts, nil
}

// Post is the resolver for the post field.
func (r *queryResolver) Post(ctx context.Context, id string) (*model.Post, error) {
	_, err := uuid.Parse(id)
	if err != nil {
		return nil, fmt.Errorf("%v id must be uuid", ErrInvalidArgument)
	}

	post, err := r.postService.GetPost(ctx, id)
	if err != nil {
		return nil, handleError(err)
	}
	return post, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
