package api

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"github.com/martyushova/posts/internal/model"
)

// SubscribeOnPost is the resolver for the SubscribeOnPost field.
func (r *subscriptionResolver) SubscribeOnPost(ctx context.Context, postID string) (<-chan *model.Comment, error) {
	comments, err := r.commentService.SubscribeOnPost(ctx, postID)
	if err != nil {
		return nil, handleError(err)
	}

	return comments, nil
}

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type subscriptionResolver struct{ *Resolver }
