// Code generated by MockGen. DO NOT EDIT.
// Source: deps.go
//
// Generated by this command:
//
//	mockgen -source deps.go -destination mocks/deps.mock.go -package=mock_comment_service
//

// Package mock_comment_service is a generated GoMock package.
package mock_comment_service

import (
	context "context"
	reflect "reflect"

	model "github.com/martyushova/posts/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockcommentRepository is a mock of commentRepository interface.
type MockcommentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockcommentRepositoryMockRecorder
	isgomock struct{}
}

// MockcommentRepositoryMockRecorder is the mock recorder for MockcommentRepository.
type MockcommentRepositoryMockRecorder struct {
	mock *MockcommentRepository
}

// NewMockcommentRepository creates a new mock instance.
func NewMockcommentRepository(ctrl *gomock.Controller) *MockcommentRepository {
	mock := &MockcommentRepository{ctrl: ctrl}
	mock.recorder = &MockcommentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcommentRepository) EXPECT() *MockcommentRepositoryMockRecorder {
	return m.recorder
}

// CreateComment mocks base method.
func (m *MockcommentRepository) CreateComment(ctx context.Context, userID string, comment *model.Comment) (*model.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateComment", ctx, userID, comment)
	ret0, _ := ret[0].(*model.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateComment indicates an expected call of CreateComment.
func (mr *MockcommentRepositoryMockRecorder) CreateComment(ctx, userID, comment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateComment", reflect.TypeOf((*MockcommentRepository)(nil).CreateComment), ctx, userID, comment)
}

// ListComments mocks base method.
func (m *MockcommentRepository) ListComments(ctx context.Context, postID string, limit, offset int32) ([]*model.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListComments", ctx, postID, limit, offset)
	ret0, _ := ret[0].([]*model.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListComments indicates an expected call of ListComments.
func (mr *MockcommentRepositoryMockRecorder) ListComments(ctx, postID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListComments", reflect.TypeOf((*MockcommentRepository)(nil).ListComments), ctx, postID, limit, offset)
}
