// Code generated by MockGen. DO NOT EDIT.
// Source: deps.go
//
// Generated by this command:
//
//	mockgen -source deps.go -destination mocks/deps.mock.go -package=mock_post_service
//

// Package mock_post_service is a generated GoMock package.
package mock_post_service

import (
	context "context"
	reflect "reflect"

	model "github.com/martyushova/posts/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockpostRepository is a mock of postRepository interface.
type MockpostRepository struct {
	ctrl     *gomock.Controller
	recorder *MockpostRepositoryMockRecorder
	isgomock struct{}
}

// MockpostRepositoryMockRecorder is the mock recorder for MockpostRepository.
type MockpostRepositoryMockRecorder struct {
	mock *MockpostRepository
}

// NewMockpostRepository creates a new mock instance.
func NewMockpostRepository(ctrl *gomock.Controller) *MockpostRepository {
	mock := &MockpostRepository{ctrl: ctrl}
	mock.recorder = &MockpostRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockpostRepository) EXPECT() *MockpostRepositoryMockRecorder {
	return m.recorder
}

// CreatePost mocks base method.
func (m *MockpostRepository) CreatePost(ctx context.Context, userID string, post *model.Post) (*model.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePost", ctx, userID, post)
	ret0, _ := ret[0].(*model.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePost indicates an expected call of CreatePost.
func (mr *MockpostRepositoryMockRecorder) CreatePost(ctx, userID, post any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePost", reflect.TypeOf((*MockpostRepository)(nil).CreatePost), ctx, userID, post)
}

// GetPost mocks base method.
func (m *MockpostRepository) GetPost(ctx context.Context, postID string) (*model.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPost", ctx, postID)
	ret0, _ := ret[0].(*model.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPost indicates an expected call of GetPost.
func (mr *MockpostRepositoryMockRecorder) GetPost(ctx, postID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPost", reflect.TypeOf((*MockpostRepository)(nil).GetPost), ctx, postID)
}

// ListPosts mocks base method.
func (m *MockpostRepository) ListPosts(ctx context.Context) ([]*model.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPosts", ctx)
	ret0, _ := ret[0].([]*model.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPosts indicates an expected call of ListPosts.
func (mr *MockpostRepositoryMockRecorder) ListPosts(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPosts", reflect.TypeOf((*MockpostRepository)(nil).ListPosts), ctx)
}
