// Code generated by MockGen. DO NOT EDIT.
// Source: deps.go
//
// Generated by this command:
//
//	mockgen -source deps.go -destination mocks/deps.mock.go -package=mock_api
//

// Package mock_api is a generated GoMock package.
package mock_api

import (
	context "context"
	reflect "reflect"

	model "github.com/martyushova/posts/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockpostService is a mock of postService interface.
type MockpostService struct {
	ctrl     *gomock.Controller
	recorder *MockpostServiceMockRecorder
	isgomock struct{}
}

// MockpostServiceMockRecorder is the mock recorder for MockpostService.
type MockpostServiceMockRecorder struct {
	mock *MockpostService
}

// NewMockpostService creates a new mock instance.
func NewMockpostService(ctrl *gomock.Controller) *MockpostService {
	mock := &MockpostService{ctrl: ctrl}
	mock.recorder = &MockpostServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockpostService) EXPECT() *MockpostServiceMockRecorder {
	return m.recorder
}

// CreatePost mocks base method.
func (m *MockpostService) CreatePost(ctx context.Context, userID string, post *model.Post) (*model.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePost", ctx, userID, post)
	ret0, _ := ret[0].(*model.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePost indicates an expected call of CreatePost.
func (mr *MockpostServiceMockRecorder) CreatePost(ctx, userID, post any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePost", reflect.TypeOf((*MockpostService)(nil).CreatePost), ctx, userID, post)
}

// GetPost mocks base method.
func (m *MockpostService) GetPost(ctx context.Context, postID string) (*model.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPost", ctx, postID)
	ret0, _ := ret[0].(*model.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPost indicates an expected call of GetPost.
func (mr *MockpostServiceMockRecorder) GetPost(ctx, postID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPost", reflect.TypeOf((*MockpostService)(nil).GetPost), ctx, postID)
}

// ListPosts mocks base method.
func (m *MockpostService) ListPosts(ctx context.Context) ([]*model.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPosts", ctx)
	ret0, _ := ret[0].([]*model.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPosts indicates an expected call of ListPosts.
func (mr *MockpostServiceMockRecorder) ListPosts(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPosts", reflect.TypeOf((*MockpostService)(nil).ListPosts), ctx)
}

// MockcommentService is a mock of commentService interface.
type MockcommentService struct {
	ctrl     *gomock.Controller
	recorder *MockcommentServiceMockRecorder
	isgomock struct{}
}

// MockcommentServiceMockRecorder is the mock recorder for MockcommentService.
type MockcommentServiceMockRecorder struct {
	mock *MockcommentService
}

// NewMockcommentService creates a new mock instance.
func NewMockcommentService(ctrl *gomock.Controller) *MockcommentService {
	mock := &MockcommentService{ctrl: ctrl}
	mock.recorder = &MockcommentServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcommentService) EXPECT() *MockcommentServiceMockRecorder {
	return m.recorder
}

// CreateComment mocks base method.
func (m *MockcommentService) CreateComment(ctx context.Context, userID string, comment *model.Comment) (*model.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateComment", ctx, userID, comment)
	ret0, _ := ret[0].(*model.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateComment indicates an expected call of CreateComment.
func (mr *MockcommentServiceMockRecorder) CreateComment(ctx, userID, comment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateComment", reflect.TypeOf((*MockcommentService)(nil).CreateComment), ctx, userID, comment)
}

// ListComments mocks base method.
func (m *MockcommentService) ListComments(ctx context.Context, postID string, limit, offset int32) ([]*model.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListComments", ctx, postID, limit, offset)
	ret0, _ := ret[0].([]*model.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListComments indicates an expected call of ListComments.
func (mr *MockcommentServiceMockRecorder) ListComments(ctx, postID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListComments", reflect.TypeOf((*MockcommentService)(nil).ListComments), ctx, postID, limit, offset)
}

// SubscribeOnPost mocks base method.
func (m *MockcommentService) SubscribeOnPost(ctx context.Context, postID string) (<-chan *model.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeOnPost", ctx, postID)
	ret0, _ := ret[0].(<-chan *model.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubscribeOnPost indicates an expected call of SubscribeOnPost.
func (mr *MockcommentServiceMockRecorder) SubscribeOnPost(ctx, postID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeOnPost", reflect.TypeOf((*MockcommentService)(nil).SubscribeOnPost), ctx, postID)
}
