// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CommentInput struct {
	Text            string  `json:"text"`
	PostID          string  `json:"postID"`
	ParentCommentID *string `json:"parentCommentID,omitempty"`
}

type Mutation struct {
}

type PostInput struct {
	Text            string `json:"text"`
	CommentsAllowed bool   `json:"commentsAllowed"`
}

type Query struct {
}

type Subscription struct {
}
